# Generated by Django 5.0.2 on 2024-04-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_videocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
